# This is a basic workflow to help you get started with Actions

name: Covid19CO Tweet

# Controls when the action will run. Triggers the workflow on Schedule
# At every 15th minute
on:
  schedule:
    - cron: '*/5 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "covid19co-tweet"
  covid19co-tweet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    # Setup Python
    - name: Setup Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    
    # Install Python Dependencies
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    # Run Covid19CO Tweet Script
    - name: Run Covid19CO Tweet Script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TWEET_CONSUMER_KEY: ${{ secrets.TWEET_CONSUMER_KEY }}
        TWEET_CONSUMER_SECRET: ${{ secrets.TWEET_CONSUMER_SECRET }}
        TWEET_ACCESS_TOKEN: ${{ secrets.TWEET_ACCESS_TOKEN }}
        TWEET_ACCESS_TOKEN_SECRET: ${{ secrets.TWEET_ACCESS_TOKEN_SECRET }}
        KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
        KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
      run: |
        # Run Covid19CO Tweet Script
        ./run.sh
        echo ""
        # Check any change
        if [[ $(git status --porcelain) ]]; then
          echo "Covid19CO Tweet Updated"
          git config --global user.email 'sebaxtianrioss@gmail.com'
          git config --global user.name 'Sebastian Rios Sabogal'
          git add .
          git commit -m "Updated at $(date)"
          git push origin master
        else
          echo 'Not Changes'
        fi
        echo ""
